import { type Platform } from "@/lib/platforms"
import {
  YouTubeIcon,
  SpotifyIcon,
  InstagramIcon,
  TwitterIcon,
  TikTokIcon,
  GitHubIcon,
  LinkedInIcon,
  DiscordIcon,
  TwitchIcon,
  FacebookIcon,
  WhatsAppIcon,
  TelegramIcon,
  DribbbleIcon,
  BehanceIcon,
  FigmaIcon,
  NotionIcon,
  MediumIcon,
  SubstackIcon,
  PatreonIcon,
  BuyMeACoffeeIcon,
  RedditIcon,
  BlueskyIcon,
  ThreadsIcon,
  SnapchatIcon,
  PinterestIcon,
  VimeoIcon,
  SoundCloudIcon,
  BandcampIcon,
  AppleMusicIcon,
  DeezerIcon,
  TidalIcon,
  MastodonIcon,
  ProductHuntIcon,
  StackOverflowIcon,
  CodePenIcon,
  GitLabIcon,
  BitbucketIcon,
  DevToIcon,
  HashnodeIcon,
  PolyworkIcon,
  LinktreeIcon,
  BeaconsIcon,
  CarrdIcon,
  KofiIcon,
  GumroadIcon,
  EtsyIcon,
  ShopifyIcon,
  KickstarterIcon,
  IndiegogoIcon,
  OnlyFansIcon,
  FanslyIcon,
  TwilioIcon,
  SlackIcon,
  ZoomIcon,
  CalendlyIcon,
  CalIcon,
  LinkIcon,
} from "./platform-icons"

interface PlatformIconProps {
  platform: Platform
  className?: string
}

const iconMap: Record<Platform, React.ComponentType<{ className?: string }>> = {
  youtube: YouTubeIcon,
  spotify: SpotifyIcon,
  instagram: InstagramIcon,
  twitter: TwitterIcon,
  tiktok: TikTokIcon,
  github: GitHubIcon,
  linkedin: LinkedInIcon,
  discord: DiscordIcon,
  twitch: TwitchIcon,
  facebook: FacebookIcon,
  whatsapp: WhatsAppIcon,
  telegram: TelegramIcon,
  dribbble: DribbbleIcon,
  behance: BehanceIcon,
  figma: FigmaIcon,
  notion: NotionIcon,
  medium: MediumIcon,
  substack: SubstackIcon,
  patreon: PatreonIcon,
  buymeacoffee: BuyMeACoffeeIcon,
  reddit: RedditIcon,
  bluesky: BlueskyIcon,
  threads: ThreadsIcon,
  snapchat: SnapchatIcon,
  pinterest: PinterestIcon,
  vimeo: VimeoIcon,
  soundcloud: SoundCloudIcon,
  bandcamp: BandcampIcon,
  applemusic: AppleMusicIcon,
  deezer: DeezerIcon,
  tidal: TidalIcon,
  mastodon: MastodonIcon,
  producthunt: ProductHuntIcon,
  stackoverflow: StackOverflowIcon,
  codepen: CodePenIcon,
  gitlab: GitLabIcon,
  bitbucket: BitbucketIcon,
  devto: DevToIcon,
  hashnode: HashnodeIcon,
  polywork: PolyworkIcon,
  linktree: LinktreeIcon,
  beacons: BeaconsIcon,
  carrd: CarrdIcon,
  kofi: KofiIcon,
  gumroad: GumroadIcon,
  etsy: EtsyIcon,
  shopify: ShopifyIcon,
  kickstarter: KickstarterIcon,
  indiegogo: IndiegogoIcon,
  onlyfans: OnlyFansIcon,
  fansly: FanslyIcon,
  twilio: TwilioIcon,
  slack: SlackIcon,
  zoom: ZoomIcon,
  calendly: CalendlyIcon,
  cal: CalIcon,
  link: LinkIcon,
  header: LinkIcon, // Header no usa icono pero necesita un fallback
}

export function PlatformIcon({ platform, className }: PlatformIconProps) {
  const Icon = iconMap[platform] || LinkIcon
  return <Icon className={className} />
}

// Re-export individual icons for direct use
export * from "./platform-icons"
